### ISSUE TITLE
exec ./entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by StreamZero** [JACOBSMILE/tmodloader1.4#10]
Hi, i'm trying to make a server on docker, but when i try to docker run it i get a "exec format error" on ./entrypoint.sh.
I've tried the provided docker run example and also customized it but in both cases it crash with the same message and restart in a loop.
I'm using the latest docker version on Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-1030-oracle aarch64) in a Oracle cloud server.

**Comment by JACOBSMILE** [comment]
I had this happen with line endings being CRLF not LF. I'll take another look and see if GitHub somehow reverted back to CRLF in the files.
