### ISSUE TITLE
Wrong options for difficulty

### ISSUE THREAD

**Issue by lachlancollins** [JACOBSMILE/tmodloader1.4#17]
Hi @JACOBSMILE , thanks so much for maintaining this! I noticed the TMOD_DIFFICULTY options are listed as "1 = Normal, 2 = Master, 3 = Journey", however the [wiki](https://terraria.wiki.gg/wiki/Guide:Setting_up_a_Terraria_server#Making_a_configuration_file) lists the difficulty options as "0(classic), 1(expert), 2(master), 3(journey)". I figured some people might get a shock when their "normal" world is actually expert!

**Comment by JACOBSMILE** [comment]
This was a good catch. I am updating the documentation right now.

**Comment by JACOBSMILE** [comment]
Fixed.

**Comment by SeppiDamgaard** [comment]
I would like to add that this is still a thing on the UnRaid app
"Container Variable: TMOD_DIFFICULTY
When generating a new world (and only when generating a new world), this variable will set the difficulty of the world. 1 = Normal, 2 = Master, 3 = Journey."

**Comment by JACOBSMILE** [comment]
Thanks, I will adjust the unraid xml for this. Only new pulls of the app will reflect the change.
