### ISSUE TITLE
enabled.json moved location

### ISSUE THREAD

**Issue by matthew-jones-uk** [JACOBSMILE/tmodloader1.4#25]
Just created a fresh server, following the instructions in the README. Everything downloads okay and the SYSTEM messages state that mods are being enabled, however doing `/modlist` yields no enabled mods. There's also a 
```
Did not find enabled.json file
```
in the logfile.

I'm not completely sure how configuration works but I looked at `~/.local/share/Terraria/` and spotted a new `~/.local/share/Terraria/tModLoader1.4.3`. Moving the `enabled.json` to this new location seems to work fine. [This ](https://github.com/tModLoader/tModLoader/issues/3621)issue seems to confirm what I'm observing.

I think maybe
`enabledpath=$HOME/.local/share/Terraria/tModLoader/Mods/enabled.json` needs changing to `enabledpath=$HOME/.local/share/Terraria/tModLoader1.4.3/Mods/enabled.json` in `entrypoint.sh`? This might just be a temporary change and may need to be reverted when 1.4.4 is released.

**Comment by JACOBSMILE** [comment]
I'll have to review this. This is a breaking change by tModLoader if they indeed moved the directory.

**Comment by soveriegn3** [comment]
I can second this issue, I was trying to set up a server and was having issues all day on the 16th. I kept seeing the "enabled.json" error and ignored it, the fix in this thread got the server to correctly load mods. The tmodloader 1.4.3/1.4.4 branch changes seem to be causing a lot of issues.

**Comment by JACOBSMILE** [comment]
This should be fixed now, please reopen if it does not work after a fresh build of :latest.
