### ISSUE TITLE
Server is not starting with mods

### ISSUE THREAD

**Issue by ySteini** [JACOBSMILE/tmodloader1.4#26]
Hi, 
I have an issue that the server is enabling the mods but doesn't start with them. 
If I join the Terraria World none of the Mods are working neither can I see them in the /modlist command.

Here are the Logs:
![Screenshot 2023-07-18 122002](https://github.com/JACOBSMILE/tmodloader1.4/assets/74825963/1708667f-9427-40fd-adf5-a888d2e6b461)

**Comment by ChrissprayCode** [comment]
Second this. I am currently running it on Unraid and I am having the exact same issue, log file looks identical.
Mods have been downloaded and are in a  \Workshop\steamapps\workshop\content file

**Comment by JACOBSMILE** [comment]
Will review. TModLoader has committed a breaking change to their GitHub I have to account for.

**Comment by JACOBSMILE** [comment]
This should be fixed now, please reopen if it does not work after a fresh build of :latest.
