### ISSUE TITLE
Can i add a new mod without it generating a new World?

### ISSUE THREAD

**Issue by ySteini** [JACOBSMILE/tmodloader1.4#35]
Can i add a new mod without it generating a new World?
because I want to add the magic storage mod to the server but i dont want to play on a new World.

**Comment by donottrolling** [comment]
I'm curious about this too!

**Comment by JACOBSMILE** [comment]
You can simply add a mod to the download and enabled mods environment variables and reboot the server. I will advise be careful of what mods you install, as some can have more damaging affects to an already generated world then others. I'd take a backup first at the very least.
