### ISSUE TITLE
server quit

### ISSUE THREAD

**Issue by KiritanTakechi** [JACOBSMILE/tmodloader1.4#42]
Why does the server sometimes inexplicably quit normally code 0

**Comment by KiritanTakechi** [comment]
`"TMOD_AUTODOWNLOAD=2561619075,2563815443,2565540604,2565770836,2568214360,2576847291,2597324266,2603400287,2619954303,2645058109,2669644269,2670628346,2687866031,2689434541,2787632488,2792933897,2797518634,2803487213,2805399398,2815010161,2816694149,2827634634,2827999994,2831179995,2832487441,2838188064,2847872897,2848614204,2877850919,2923689066,2930931197,2938711389,2973922820,2984622072,2984645790,2985635894,2994432542,2995928077,3001327863,3001519109,3001536716,3001692619,3006139970,3008407784,3013337643,2599842771"`

**Comment by JACOBSMILE** [comment]
Do you have any logs of further information to share?

**Comment by JACOBSMILE** [comment]
Closing, no further information.
