### ISSUE TITLE
Add support for modifying the port of the server

### ISSUE THREAD

**Issue by MwenDavo** [JACOBSMILE/tmodloader1.4#49]
It would be a nice addition if you could send the port that the server will use as a environment variable, instead of being forced to 7777.

**Comment by JACOBSMILE** [comment]
Hi, yes I can look at it this weekend. Should be easy enough.

**Comment by JACOBSMILE** [comment]
This should be included now. There is a new environment variable TMOD_PORT you can use to override the default port of 7777. Make sure to change your port mapping from the host to the container.
