### ISSUE TITLE
Wrong MOD enabling parameter in the docker-compose-yml

### ISSUE THREAD

**Issue by Bluep3D** [JACOBSMILE/tmodloader1.4#5]
Hi!

In the docker-compose.yml, the following is set:
      Enable the Calamity mod and CalamityMusic mod.
      - "TMOD_LOADMODS=2824688072,2824688266"
      
      This does not load the mods, only works after changing the parameter to the same as in the documentation:
      - TMOD_ENABLEDMODS=2824688072,2824688266

**Comment by JACOBSMILE** [comment]
Fixed in #7 . Thanks!
