### ISSUE TITLE
Simple question regarding port change.

### ISSUE THREAD

**Issue by 480sdrg** [JACOBSMILE/tmodloader1.4#50]
Is there anyway to change the port in the container environment variables or is there a different way?
Port 7777 doesn't work with TrueNAS Scale and its integrated container feature as it requires all ports to be above 9000, I think it has to do with Kubernetes. Thank you for your work.

**Comment by JACOBSMILE** [comment]
Hi, yes I can look at it this weekend. Should be easy enough.

**Comment by JACOBSMILE** [comment]
My apologies. I've been down with the flu and haven't gotten the chance yet. I will soon though.

**Comment by JACOBSMILE** [comment]
This should be included now. There is a new environment variable TMOD_PORT you can use to override the default port of 7777. Make sure to change your port mapping from the host to the container.
