### ISSUE TITLE
dot net install seems to be broken

### ISSUE THREAD

**Issue by DualDier** [JACOBSMILE/tmodloader1.4#58]
Pulled :latest and it appears to have broken the dotnet updater process. Fails to update and then the container exits.

(Thank you for this container, loving it so far.)

**Comment by Bjorn-Visser** [comment]
same issue

**Comment by DualDier** [comment]
> same issue
> 
> ```
> [SYSTEM] Finished loading mods.
> tModLoader is launching with the following command:
> /terraria-server/LaunchUtils/ScriptCaller.sh -server -tmlsavedirectory "/data/tModLoader" -steamworkshopfolder "/data/steamMods/steamapps/workshop" -config "/terraria-server/serverconfig.txt"
> You are on platform: "Linux" arch: "x86_64"
> Logging to /terraria-server/tModLoader-Logs/Launch.log
> Fixing Environment Issues
> Success!
> Verifying .NET....
> This may take a few moments.
> Parsing .NET version requirements from runtimeconfig.json
> Success! dotnet_version=8.0.0
> Last Run Attempt Failed to Start tModLoader. Deleting dotnet_dir and resetting
> Checking for old .NET versions to remove from folder
> Cleanup Complete
> Checking dotnet install...
> Update Required. Will now attempt downloading using official scripts.
> This can take up to 5 minutes
> Dotnet should be present in "/terraria-server/dotnet"
> Download of portable dotnet runtime seems to have failed,
> Proceeding will probably fall back to system wide installed runtime
> Attempting Launch...
> Launched Using System Dotnet. Launch command: dotnet tModLoader.dll "-server -tmlsavedirectory /data/tModLoader -steamworkshopfolder /data/steamMods/steamapps/workshop -config /terraria-server/serverconfig.txt"
> 
> ** Press ANY KEY to close this window ** 
> ```

Yep I get the exact same issue..tried going back a few versions but it was doing the same thing.

**Comment by DualDier** [comment]
Closing. Issue was due to dot net outage. Dot net is back up. This can be closed.
