### ISSUE TITLE
How to choose world evil？

### ISSUE THREAD

**Issue by zhangxyiang** [JACOBSMILE/tmodloader1.4#59]
1       Random
2       Corrupt
3       Crimson

**Comment by JACOBSMILE** [comment]
The Terraria Dedicated Server provides no way to declare the world evil during creation. A workaround would be to create the world locally on your game client, and then upload the world file to the server's mapped directory with the name specified in the Compose File, or the environment variables. If Terraria ever adds such an option to the dedicated server, I'll add it into this project as well.
